### ISSUE TITLE
Redesign the portfolio using NextJS

### ISSUE THREAD

**Issue by maheshj01** [maheshj01/portfolio#4]
### Todo
following list items will ensure the task is complete
- [x] Add Experience Section
- [x] Redesign proper projects section
- [x] Connect form to a database and trigger email
- [ ] Fetch Social Profiles dynamically
- [x] Dark mode support
- [x] Include Github contribution graph

**Comment by maheshj01** [comment]
[Projects Design Inspiration
](https://dribbble.com/maheshmnj)
Projects will auto slide in circle and will stop on Focus and on Tap the selected project will Fly in on Top

![image](https://github.com/maheshmnj/maheshmnj.github.io/assets/31410839/56cb2104-ad83-489e-bdba-ec8279becc22)

**Comment by maheshj01** [comment]
Social app links card generator
- [ ] [Stackoverflow profile generator](https://stackoverflow-readme-profile.vercel.app/profile)

**Comment by maheshj01** [comment]
Send form detail to email using emailjs https://www.emailjs.com/docs/introduction/how-does-emailjs-work/

**Comment by maheshj01** [comment]
Github contribution graph can be built using the graphql api

see: https://stackoverflow.com/questions/18262288/finding-total-contributions-of-a-user-from-github-api
https://medium.com/@yuichkun/how-to-retrieve-contribution-graph-data-from-the-github-api-dc3a151b4af

Also add leetcode contributions: https://leetcode.com/discuss/general-discussion/1297705/is-there-public-api-endpoints-available-for-leetcode

**Comment by Ayushrai83** [comment]
https://gurukuldeveloperportfolio.netlify.app/      
checkout this portfolio and let me know if you want these in your portfolio

**Comment by maheshj01** [comment]
Hi @Ayushrai83 Want what? Are you interested to contribute something to this project?

**Comment by Ayushrai83** [comment]
@maheshj01 yes i am fresher just want to join community and work together to enhance my skills 
I want to work on open source projects with you under your guidance

**Comment by maheshj01** [comment]
Sure, But I think this is not the right project to contribute, If you are interested in React I am currently working on 
https://github.com/maheshj01/github-freak to visualize github contributions, Let me know if you find this project interesting and we can discuss further in a issue thread.

**Comment by maheshj01** [comment]
Migrate the project to NextJS inorder to index pages for SEO
